# This is a basic workflow to help you get started with Actions

name: Deploy to GCS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_CREDS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Install deps'
        run: npm install

      - name: 'Build bundle'
        run: npm run build

      - name: 'Upload to GCS'
        run: |
          gcloud --quiet alpha storage cp not-found.html gs://www.alt-text.org/
          gcloud --quiet alpha storage cp signed-up.html gs://www.alt-text.org/
          gcloud --quiet alpha storage cp --recursive public gs://www.alt-text.org/
          gcloud --quiet alpha storage cp --recursive favicon gs://www.alt-text.org/
          gcloud --quiet alpha storage cp --recursive images gs://www.alt-text.org/
          gcloud --quiet alpha storage cp --recursive style gs://www.alt-text.org/
          gcloud --quiet alpha storage cp --recursive dist gs://www.alt-text.org/
